// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser, urlSearchParamsBodySerializer, formDataBodySerializer } from '@hey-api/client-axios';
import type { AuthJwtLoginData, AuthJwtLoginError, AuthJwtLoginResponse, AuthJwtLogoutError, AuthJwtLogoutResponse, RegisterRegisterData, RegisterRegisterError, RegisterRegisterResponse, ResetForgotPasswordData, ResetForgotPasswordError, ResetForgotPasswordResponse, ResetResetPasswordData, ResetResetPasswordError, ResetResetPasswordResponse, VerifyRequestTokenData, VerifyRequestTokenError, VerifyRequestTokenResponse, VerifyVerifyData, VerifyVerifyError, VerifyVerifyResponse, UsersCurrentUserError, UsersCurrentUserResponse, UsersPatchCurrentUserData, UsersPatchCurrentUserError, UsersPatchCurrentUserResponse, UsersUserData, UsersUserError, UsersUserResponse, UsersPatchUserData, UsersPatchUserError, UsersPatchUserResponse, UsersDeleteUserData, UsersDeleteUserError, UsersDeleteUserResponse, ReadItemError, ReadItemResponse, CreateItemData, CreateItemError, CreateItemResponse, DeleteItemData, DeleteItemError, DeleteItemResponse, UploadFileData, UploadFileError, UploadFileResponse, GetFileDownloadUrlData, GetFileDownloadUrlError, GetFileDownloadUrlResponse, SendEmailCodeData, SendEmailCodeError, SendEmailCodeResponse, SendPhoneCodeData, SendPhoneCodeError, SendPhoneCodeResponse, RegisterWithCodeData, RegisterWithCodeError, RegisterWithCodeResponse, LoginWithPhoneData, LoginWithPhoneError, LoginWithPhoneResponse, ListSmsData, ListSmsError, ListSmsResponse, SmsStatsError, SmsStatsResponse2, SmsPhonesError, SmsPhonesResponse, GetSmsData, GetSmsError, GetSmsResponse, DeleteSmsData, DeleteSmsError, DeleteSmsResponse, UploadSmsData, UploadSmsError, UploadSmsResponse, BatchUploadSmsData, BatchUploadSmsError, BatchUploadSmsResponse, StarSmsData, StarSmsError, StarSmsResponse, BatchStarSmsData, BatchStarSmsError, BatchStarSmsResponse, BatchDeleteSmsData, BatchDeleteSmsError, BatchDeleteSmsResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<AuthJwtLoginData, ThrowOnError>) => {
    return (options?.client ?? client).post<AuthJwtLoginResponse, AuthJwtLoginError, ThrowOnError>({
        ...options,
        ...urlSearchParamsBodySerializer,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        },
        url: '/auth/jwt/login'
    });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<AuthJwtLogoutResponse, AuthJwtLogoutError, ThrowOnError>({
        ...options,
        url: '/auth/jwt/logout'
    });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RegisterRegisterData, ThrowOnError>) => {
    return (options?.client ?? client).post<RegisterRegisterResponse, RegisterRegisterError, ThrowOnError>({
        ...options,
        url: '/auth/register'
    });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ResetForgotPasswordData, ThrowOnError>) => {
    return (options?.client ?? client).post<ResetForgotPasswordResponse, ResetForgotPasswordError, ThrowOnError>({
        ...options,
        url: '/auth/forgot-password'
    });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<ResetResetPasswordData, ThrowOnError>) => {
    return (options?.client ?? client).post<ResetResetPasswordResponse, ResetResetPasswordError, ThrowOnError>({
        ...options,
        url: '/auth/reset-password'
    });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<VerifyRequestTokenData, ThrowOnError>) => {
    return (options?.client ?? client).post<VerifyRequestTokenResponse, VerifyRequestTokenError, ThrowOnError>({
        ...options,
        url: '/auth/request-verify-token'
    });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<VerifyVerifyData, ThrowOnError>) => {
    return (options?.client ?? client).post<VerifyVerifyResponse, VerifyVerifyError, ThrowOnError>({
        ...options,
        url: '/auth/verify'
    });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<UsersCurrentUserResponse, UsersCurrentUserError, ThrowOnError>({
        ...options,
        url: '/users/me'
    });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UsersPatchCurrentUserData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UsersPatchCurrentUserResponse, UsersPatchCurrentUserError, ThrowOnError>({
        ...options,
        url: '/users/me'
    });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UsersUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<UsersUserResponse, UsersUserError, ThrowOnError>({
        ...options,
        url: '/users/{id}'
    });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UsersPatchUserData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UsersPatchUserResponse, UsersPatchUserError, ThrowOnError>({
        ...options,
        url: '/users/{id}'
    });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UsersDeleteUserData, ThrowOnError>) => {
    return (options?.client ?? client).delete<UsersDeleteUserResponse, UsersDeleteUserError, ThrowOnError>({
        ...options,
        url: '/users/{id}'
    });
};

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadItemResponse, ReadItemError, ThrowOnError>({
        ...options,
        url: '/items/'
    });
};

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<CreateItemData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateItemResponse, CreateItemError, ThrowOnError>({
        ...options,
        url: '/items/'
    });
};

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteItemData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteItemResponse, DeleteItemError, ThrowOnError>({
        ...options,
        url: '/items/{item_id}'
    });
};

/**
 * Upload File
 */
export const uploadFile = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UploadFileData, ThrowOnError>) => {
    return (options?.client ?? client).post<UploadFileResponse, UploadFileError, ThrowOnError>({
        ...options,
        ...formDataBodySerializer,
        headers: {
            'Content-Type': null,
            ...options?.headers
        },
        url: '/files/upload'
    });
};

/**
 * Get File Download Url
 */
export const getFileDownloadUrl = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetFileDownloadUrlData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFileDownloadUrlResponse, GetFileDownloadUrlError, ThrowOnError>({
        ...options,
        url: '/files/{file_id}/download'
    });
};

/**
 * Send Email Code
 */
export const sendEmailCode = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SendEmailCodeData, ThrowOnError>) => {
    return (options?.client ?? client).post<SendEmailCodeResponse, SendEmailCodeError, ThrowOnError>({
        ...options,
        url: '/auth/send-email-code'
    });
};

/**
 * Send Phone Code
 */
export const sendPhoneCode = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<SendPhoneCodeData, ThrowOnError>) => {
    return (options?.client ?? client).post<SendPhoneCodeResponse, SendPhoneCodeError, ThrowOnError>({
        ...options,
        url: '/auth/send-phone-code'
    });
};

/**
 * Register With Code
 */
export const registerWithCode = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<RegisterWithCodeData, ThrowOnError>) => {
    return (options?.client ?? client).post<RegisterWithCodeResponse, RegisterWithCodeError, ThrowOnError>({
        ...options,
        url: '/auth/register-with-code'
    });
};

/**
 * Login With Phone
 */
export const loginWithPhone = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<LoginWithPhoneData, ThrowOnError>) => {
    return (options?.client ?? client).post<LoginWithPhoneResponse, LoginWithPhoneError, ThrowOnError>({
        ...options,
        url: '/auth/login/phone'
    });
};

/**
 * List Sms
 */
export const listSms = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<ListSmsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSmsResponse, ListSmsError, ThrowOnError>({
        ...options,
        url: '/sms/'
    });
};

/**
 * Sms Stats
 */
export const smsStats = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<SmsStatsResponse2, SmsStatsError, ThrowOnError>({
        ...options,
        url: '/sms/stats'
    });
};

/**
 * Sms Phones
 */
export const smsPhones = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<SmsPhonesResponse, SmsPhonesError, ThrowOnError>({
        ...options,
        url: '/sms/phones'
    });
};

/**
 * Get Sms
 */
export const getSms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetSmsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSmsResponse, GetSmsError, ThrowOnError>({
        ...options,
        url: '/sms/{sms_id}'
    });
};

/**
 * Delete Sms
 */
export const deleteSms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<DeleteSmsData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteSmsResponse, DeleteSmsError, ThrowOnError>({
        ...options,
        url: '/sms/{sms_id}'
    });
};

/**
 * Upload Sms
 */
export const uploadSms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UploadSmsData, ThrowOnError>) => {
    return (options?.client ?? client).post<UploadSmsResponse, UploadSmsError, ThrowOnError>({
        ...options,
        url: '/sms/upload'
    });
};

/**
 * Batch Upload Sms
 */
export const batchUploadSms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<BatchUploadSmsData, ThrowOnError>) => {
    return (options?.client ?? client).post<BatchUploadSmsResponse, BatchUploadSmsError, ThrowOnError>({
        ...options,
        url: '/sms/upload/batch'
    });
};

/**
 * Star Sms
 */
export const starSms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<StarSmsData, ThrowOnError>) => {
    return (options?.client ?? client).patch<StarSmsResponse, StarSmsError, ThrowOnError>({
        ...options,
        url: '/sms/{sms_id}/star'
    });
};

/**
 * Batch Star Sms
 */
export const batchStarSms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<BatchStarSmsData, ThrowOnError>) => {
    return (options?.client ?? client).post<BatchStarSmsResponse, BatchStarSmsError, ThrowOnError>({
        ...options,
        url: '/sms/batch-star'
    });
};

/**
 * Batch Delete Sms
 */
export const batchDeleteSms = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<BatchDeleteSmsData, ThrowOnError>) => {
    return (options?.client ?? client).post<BatchDeleteSmsResponse, BatchDeleteSmsError, ThrowOnError>({
        ...options,
        url: '/sms/batch-delete'
    });
};