// This file is auto-generated by @hey-api/openapi-ts

export type AuthTokenResponse = {
    access_token: string;
    token_type?: string;
};

export type BearerResponse = {
    access_token: string;
    token_type: string;
};

export type Body_auth_reset_forgot_password = {
    email: string;
};

export type Body_auth_reset_reset_password = {
    token: string;
    password: string;
};

export type Body_auth_verify_request_token = {
    email: string;
};

export type Body_auth_verify_verify = {
    token: string;
};

export type Body_files_upload_file = {
    file: (Blob | File);
};

export type ErrorModel = {
    detail: (string | {
    [key: string]: (string);
});
};

export type FileDownloadResponse = {
    file_id: string;
    download_url: string;
    expires_in: number;
};

export type FileUploadResponse = {
    file_id: string;
    filename: string;
    size: number;
    mime_type: string;
    status: string;
    download_url: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    name: string;
    description?: (string | null);
    quantity?: (number | null);
};

export type ItemRead = {
    name: string;
    description?: (string | null);
    quantity?: (number | null);
    id: string;
    user_id: string;
};

export type login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type PhoneLoginRequest = {
    phone: string;
    code: string;
};

export type RegisterWithCodeRequest = {
    email: string;
    password: string;
    code: string;
};

export type RelayHealthResponse = {
    status: string;
    ws_connections: number;
};

export type RelayMessageListResponse = {
    total: number;
    page: number;
    page_size: number;
    items: Array<RelayMessageRead>;
};

export type RelayMessageRead = {
    id: string;
    pair_id: string;
    text: string;
    mode: (string | null);
    after_key: (string | null);
    smart_mode: boolean;
    smart_action: (string | null);
    delivery_status: string;
    ack_ok: (boolean | null);
    ack_error: (string | null);
    client_ip: (string | null);
    created_at: string;
};

export type RelayMessageStatsResponse = {
    total: number;
    today: number;
    delivered: number;
    pc_offline: number;
};

export type RelayPairCreateRequest = {
    device_name?: (string | null);
};

export type RelayPairCreateResponse = {
    pair_id: string;
    pair_token: string;
    agent_token: string;
    relay_ws_url: string;
    relay_agent_url: string;
    expires_at: string;
    qr_payload: RelayQrPayload;
};

export type RelayPairListResponse = {
    items: Array<RelayPairRead>;
};

export type RelayPairRead = {
    pair_id: string;
    device_name: (string | null);
    expires_at: string;
    revoked_at: (string | null);
    created_at: string;
    pc_online?: boolean;
    phone_connections?: number;
};

export type RelayPairRefreshResponse = {
    pair_token: string;
    expires_at: string;
    qr_payload: RelayQrPayload;
};

export type RelayPairStatusResponse = {
    pair_id: string;
    pc_online: boolean;
    phone_connections: number;
    last_agent_seen_at?: (string | null);
};

export type RelayQrPayload = {
    v?: number;
    mode?: string;
    ws: string;
    pair: string;
};

export type SendEmailCodeRequest = {
    email: string;
    scene?: string;
};

export type SendPhoneCodeRequest = {
    phone: string;
};

export type SmsBatchActionResponse = {
    updated?: (number | null);
    deleted?: (number | null);
};

export type SmsBatchDeleteRequest = {
    ids: Array<(string)>;
};

export type SmsBatchStarRequest = {
    ids: Array<(string)>;
    starred: boolean;
};

export type SmsBatchUploadRequest = {
    messages: Array<SmsUploadRequest>;
};

export type SmsBatchUploadResponse = {
    success: number;
    failed: number;
    ids: Array<(string)>;
};

export type SmsForwardDevice = {
    id: string;
    model: string;
    manufacturer: string;
    androidSdk: number;
    appVersion: string;
};

export type SmsForwardInboundRequest = {
    id: string;
    event: string;
    version: string;
    device: SmsForwardDevice;
    rule: SmsForwardRule;
    message: SmsForwardMessage;
    meta: SmsForwardMeta;
};

export type SmsForwardMessage = {
    from: string;
    body: string;
    timestamp: number;
    subscriptionId?: (number | null);
    simSlot?: (number | null);
    partCount?: number;
};

export type SmsForwardMeta = {
    receivedAt: number;
    sentAt: number;
    attempt?: number;
    contentLength: number;
    contentSha256: string;
};

export type SmsForwardRule = {
    id: number;
    name?: (string | null);
    senderFilter: string;
};

export type SmsListResponse = {
    total: number;
    page: number;
    page_size: number;
    items: Array<SmsRead>;
};

export type SmsRead = {
    id: string;
    phone: string;
    content: string;
    received_at: string;
    starred: boolean;
    created_at: string;
    updated_at?: (string | null);
};

export type SmsStarRequest = {
    starred: boolean;
};

export type SmsStatsResponse = {
    total: number;
    starred: number;
    today: number;
    this_week: number;
    this_month: number;
};

export type SmsUploadRequest = {
    phone: string;
    content: string;
    received_at?: (string | null);
};

export type SmsUploadResponse = {
    id: string;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_verified?: (boolean | null);
};

export type UserRead = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_verified?: boolean;
};

export type UserUpdate = {
    password?: (string | null);
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    is_verified?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuthJwtLoginData = {
    body: login;
};

export type AuthJwtLoginResponse = (BearerResponse);

export type AuthJwtLoginError = (ErrorModel | HTTPValidationError);

export type AuthJwtLogoutResponse = (unknown);

export type AuthJwtLogoutError = (unknown);

export type RegisterRegisterData = {
    body: UserCreate;
};

export type RegisterRegisterResponse = (UserRead);

export type RegisterRegisterError = (ErrorModel | HTTPValidationError);

export type ResetForgotPasswordData = {
    body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = (unknown);

export type ResetForgotPasswordError = (HTTPValidationError);

export type ResetResetPasswordData = {
    body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = (unknown);

export type ResetResetPasswordError = (ErrorModel | HTTPValidationError);

export type VerifyRequestTokenData = {
    body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = (unknown);

export type VerifyRequestTokenError = (HTTPValidationError);

export type VerifyVerifyData = {
    body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = (UserRead);

export type VerifyVerifyError = (ErrorModel | HTTPValidationError);

export type UsersCurrentUserResponse = (UserRead);

export type UsersCurrentUserError = (unknown);

export type UsersPatchCurrentUserData = {
    body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = (UserRead);

export type UsersPatchCurrentUserError = (ErrorModel | unknown | HTTPValidationError);

export type UsersUserData = {
    path: {
        id: string;
    };
};

export type UsersUserResponse = (UserRead);

export type UsersUserError = (unknown | HTTPValidationError);

export type UsersPatchUserData = {
    body: UserUpdate;
    path: {
        id: string;
    };
};

export type UsersPatchUserResponse = (UserRead);

export type UsersPatchUserError = (ErrorModel | unknown | HTTPValidationError);

export type UsersDeleteUserData = {
    path: {
        id: string;
    };
};

export type UsersDeleteUserResponse = (void);

export type UsersDeleteUserError = (unknown | HTTPValidationError);

export type ReadItemResponse = (Array<ItemRead>);

export type ReadItemError = unknown;

export type CreateItemData = {
    body: ItemCreate;
};

export type CreateItemResponse = (ItemRead);

export type CreateItemError = (HTTPValidationError);

export type DeleteItemData = {
    path: {
        item_id: string;
    };
};

export type DeleteItemResponse = (unknown);

export type DeleteItemError = (HTTPValidationError);

export type UploadFileData = {
    body: Body_files_upload_file;
};

export type UploadFileResponse = (FileUploadResponse);

export type UploadFileError = (HTTPValidationError);

export type GetFileDownloadUrlData = {
    path: {
        file_id: string;
    };
};

export type GetFileDownloadUrlResponse = (FileDownloadResponse);

export type GetFileDownloadUrlError = (HTTPValidationError);

export type SendEmailCodeData = {
    body: SendEmailCodeRequest;
};

export type SendEmailCodeResponse = (unknown);

export type SendEmailCodeError = (HTTPValidationError);

export type SendPhoneCodeData = {
    body: SendPhoneCodeRequest;
};

export type SendPhoneCodeResponse = (unknown);

export type SendPhoneCodeError = (HTTPValidationError);

export type RegisterWithCodeData = {
    body: RegisterWithCodeRequest;
};

export type RegisterWithCodeResponse = (AuthTokenResponse);

export type RegisterWithCodeError = (HTTPValidationError);

export type LoginWithPhoneData = {
    body: PhoneLoginRequest;
};

export type LoginWithPhoneResponse = (AuthTokenResponse);

export type LoginWithPhoneError = (HTTPValidationError);

export type ListSmsData = {
    query?: {
        end_time?: (string | null);
        page?: number;
        page_size?: number;
        phone?: (string | null);
        search?: (string | null);
        starred?: (boolean | null);
        start_time?: (string | null);
    };
};

export type ListSmsResponse = (SmsListResponse);

export type ListSmsError = (HTTPValidationError);

export type SmsStatsResponse2 = (SmsStatsResponse);

export type SmsStatsError = unknown;

export type SmsPhonesResponse = (Array<(string)>);

export type SmsPhonesError = unknown;

export type GetSmsData = {
    path: {
        sms_id: string;
    };
};

export type GetSmsResponse = (SmsRead);

export type GetSmsError = (HTTPValidationError);

export type DeleteSmsData = {
    path: {
        sms_id: string;
    };
};

export type DeleteSmsResponse = (unknown);

export type DeleteSmsError = (HTTPValidationError);

export type UploadSmsData = {
    body: SmsUploadRequest;
};

export type UploadSmsResponse = (SmsUploadResponse);

export type UploadSmsError = (HTTPValidationError);

export type BatchUploadSmsData = {
    body: SmsBatchUploadRequest;
};

export type BatchUploadSmsResponse = (SmsBatchUploadResponse);

export type BatchUploadSmsError = (HTTPValidationError);

export type StarSmsData = {
    body: SmsStarRequest;
    path: {
        sms_id: string;
    };
};

export type StarSmsResponse = (unknown);

export type StarSmsError = (HTTPValidationError);

export type BatchStarSmsData = {
    body: SmsBatchStarRequest;
};

export type BatchStarSmsResponse = (SmsBatchActionResponse);

export type BatchStarSmsError = (HTTPValidationError);

export type BatchDeleteSmsData = {
    body: SmsBatchDeleteRequest;
};

export type BatchDeleteSmsResponse = (SmsBatchActionResponse);

export type BatchDeleteSmsError = (HTTPValidationError);

export type InboundHealthResponse = (unknown);

export type InboundHealthError = unknown;

export type SmsInboundData = {
    body: SmsForwardInboundRequest;
    headers?: {
        'x-api-key'?: (string | null);
        'X-Sms-Forward-Device-Id'?: (string | null);
        'X-Sms-Forward-Message-Id'?: (string | null);
        'X-Sms-Forward-Rule-Id'?: (string | null);
        'X-Sms-Forward-Version'?: (string | null);
    };
};

export type SmsInboundResponse = (unknown);

export type SmsInboundError = (HTTPValidationError);

export type RelayHealthResponse2 = (RelayHealthResponse);

export type RelayHealthError = unknown;

export type ListPairsResponse = (RelayPairListResponse);

export type ListPairsError = unknown;

export type CreatePairData = {
    body: RelayPairCreateRequest;
};

export type CreatePairResponse = (RelayPairCreateResponse);

export type CreatePairError = (HTTPValidationError);

export type PairStatusData = {
    path: {
        pair_id: string;
    };
};

export type PairStatusResponse = (RelayPairStatusResponse);

export type PairStatusError = (HTTPValidationError);

export type RefreshPairTokenData = {
    path: {
        pair_id: string;
    };
};

export type RefreshPairTokenResponse = (RelayPairRefreshResponse);

export type RefreshPairTokenError = (HTTPValidationError);

export type RevokePairData = {
    path: {
        pair_id: string;
    };
};

export type RevokePairResponse = (void);

export type RevokePairError = (HTTPValidationError);

export type ListRelayMessagesData = {
    query?: {
        end_time?: (string | null);
        page?: number;
        page_size?: number;
        search?: (string | null);
        sort?: string;
        start_time?: (string | null);
    };
};

export type ListRelayMessagesResponse = (RelayMessageListResponse);

export type ListRelayMessagesError = (HTTPValidationError);

export type RelayMessageStatsResponse2 = (RelayMessageStatsResponse);

export type RelayMessageStatsError = unknown;

export type GetRelayMessageData = {
    path: {
        message_id: string;
    };
};

export type GetRelayMessageResponse = (RelayMessageRead);

export type GetRelayMessageError = (HTTPValidationError);

export type DeleteRelayMessageData = {
    path: {
        message_id: string;
    };
};

export type DeleteRelayMessageResponse = (void);

export type DeleteRelayMessageError = (HTTPValidationError);